//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\arvredd\Desktop\Prac_C_S\Training_Practice\RaviTeja\Nxopen\3D_Blocks\__BlockStyler3D_Dialogs.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: ARVREDD
//              Version: NX 2412
//              Date: 02-10-2026  (Format: mm-dd-yyyy)
//              Time: 12:36 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;


//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class _Block4Styler3D_Dialogs
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private string theDlxFileName_Cylinder;
    private string theDlxFileName_Cone;
    private string theDlxFileName_Block;
    private string theDlxFileName_Sphere;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Button BlockButton;// Block type: Button
    private NXOpen.BlockStyler.Button CylinderButton;// Block type: Button
    private NXOpen.BlockStyler.Button ConeButton;// Block type: Button
    private NXOpen.BlockStyler.Button SphereButton;// Block type: Button
    public static string blockbtn;

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public _Block4Styler3D_Dialogs()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = AppDomain.CurrentDomain.BaseDirectory + "3D_Dialogs.dlx";
            theDlxFileName_Block = AppDomain.CurrentDomain.BaseDirectory + "A_BlockCreation.dlx";
            theDlxFileName_Cylinder = AppDomain.CurrentDomain.BaseDirectory + "CylinderCreation_1.dlx";
            theDlxFileName_Cone = AppDomain.CurrentDomain.BaseDirectory + "ConeCreation_1.dlx";
            theDlxFileName_Sphere = AppDomain.CurrentDomain.BaseDirectory + "SphereCreation_1.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));

        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        _Block4Styler3D_Dialogs the__BlockStyler3D_Dialogs = null;
        try
        {
            the__BlockStyler3D_Dialogs = new _Block4Styler3D_Dialogs();
            // The following method shows the dialog immediately
            the__BlockStyler3D_Dialogs.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if (the__BlockStyler3D_Dialogs != null)
                the__BlockStyler3D_Dialogs.Dispose();
            the__BlockStyler3D_Dialogs = null;
        }

    }

    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
    public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }

    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
    {
        NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;

        try
        {
            dialogResponse = theDialog.Launch();

        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return dialogResponse;
    }

    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            BlockButton = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("BlockButton");
            CylinderButton = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("CylinderButton");
            ConeButton = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("ConeButton");
            SphereButton = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("SphereButton");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
            //BlockCreation_1 blockCreation_1 = new BlockCreation_1();
            //blockCreation_1.Launch();


            //BlockCreation_1.Main();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        A_BlockCreation theA_BlockCreation = null;
        CylinderCreation_1 theCylinderCreation_1 = null;
        ConeCreation_1 theConeCreation_1 = null;
        SphereCreation_1 theSphereCreation_1 = null;
        try
        {

            if (block == BlockButton)
            {
                theA_BlockCreation = new A_BlockCreation();
                // The following method shows the dialog immediately
                theA_BlockCreation.Launch();
            }
            else if (block == CylinderButton)
            {
                theCylinderCreation_1 = new CylinderCreation_1();
                // The following method shows the dialog immediately
                theCylinderCreation_1.Launch();
            }
            else if (block == ConeButton)
            {
                theConeCreation_1 = new ConeCreation_1();
                // The following method shows the dialog immediately
                theConeCreation_1.Launch();
            }
            else if (block == SphereButton)
            {
                theSphereCreation_1 = new SphereCreation_1();
                // The following method shows the dialog immediately
                theSphereCreation_1.Launch();

            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

}
