//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\arvredd\Desktop\Prac_C_S\Training_Practice\RaviTeja\Nxopen\Nx_tasks\BlockStylers\BlockStylers.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: ARVREDD
//              Version: NX 2412
//              Date: 02-03-2026  (Format: mm-dd-yyyy)
//              Time: 11:32 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using CreationOfBlockStylers;
using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.UIStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class BlockStylers
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.TabControl tabControl;// Block type: Tabs Page
    private NXOpen.BlockStyler.Group tabBlock;
    private NXOpen.BlockStyler.Group grpOrigin;// Block type: Group
    private NXOpen.BlockStyler.SpecifyPoint spyPoint;// Block type: Specify Point
    private NXOpen.BlockStyler.Group grpDimensions;// Block type: Group
    private NXOpen.BlockStyler.DoubleBlock dblLength;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock dblWidth;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock dblHeight;// Block type: Double
    private NXOpen.BlockStyler.Group tabCylinder;
    private NXOpen.BlockStyler.Group grpAxis;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector spyVector;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint spyPoint1;// Block type: Specify Point
    private NXOpen.BlockStyler.Group grpDimensions1;// Block type: Group
    private NXOpen.BlockStyler.DoubleBlock dblDiameter;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock dblHeight1;// Block type: Double
    private NXOpen.BlockStyler.Group tabCone;
    private NXOpen.BlockStyler.Group grpAxis1;// Block type: Group
    private NXOpen.BlockStyler.SpecifyVector spyVector1;// Block type: Specify Vector
    private NXOpen.BlockStyler.SpecifyPoint spyPoint2;// Block type: Specify Point
    private NXOpen.BlockStyler.Group grpDimensions2;// Block type: Group
    private NXOpen.BlockStyler.DoubleBlock dblBaseDiameter;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock dblTopDiameter;// Block type: Double
    private NXOpen.BlockStyler.DoubleBlock dblHeight2;// Block type: Double
    private NXOpen.BlockStyler.Group tabSphere;
    private NXOpen.BlockStyler.Group grpCenterPoint;// Block type: Group
    private NXOpen.BlockStyler.SpecifyPoint spyPoint3;// Block type: Specify Point
    private NXOpen.BlockStyler.Group grpDimension;// Block type: Group
    private NXOpen.BlockStyler.DoubleBlock dblDiameter1;// Block type: Double
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int              SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int                 SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int           SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int                 SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int                 SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int             SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int             SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int                SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int            SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int            SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int             SnapPointTypesEnabled_PointonCurve = (1 <<10);
    public static readonly int           SnapPointTypesEnabled_PointonSurface = (1 <<11);
    public static readonly int         SnapPointTypesEnabled_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesEnabled_TwocurveIntersection = (1 <<13);
    public static readonly int             SnapPointTypesEnabled_TangentPoint = (1 <<14);
    public static readonly int                    SnapPointTypesEnabled_Poles = (1 <<15);
    public static readonly int         SnapPointTypesEnabled_BoundedGridPoint = (1 <<16);
    public static readonly int         SnapPointTypesEnabled_FacetVertexPoint = (1 <<17);
    public static readonly int            SnapPointTypesEnabled_DefiningPoint = (1 <<18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int          SnapPointTypesOnByDefault_UserDefined = (1 << 0);
    public static readonly int             SnapPointTypesOnByDefault_Inferred = (1 << 1);
    public static readonly int       SnapPointTypesOnByDefault_ScreenPosition = (1 << 2);
    public static readonly int             SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int             SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int         SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int         SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int            SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int        SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int        SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int         SnapPointTypesOnByDefault_PointonCurve = (1 <<10);
    public static readonly int       SnapPointTypesOnByDefault_PointonSurface = (1 <<11);
    public static readonly int     SnapPointTypesOnByDefault_PointConstructor = (1 <<12);
    public static readonly int SnapPointTypesOnByDefault_TwocurveIntersection = (1 <<13);
    public static readonly int         SnapPointTypesOnByDefault_TangentPoint = (1 <<14);
    public static readonly int                SnapPointTypesOnByDefault_Poles = (1 <<15);
    public static readonly int     SnapPointTypesOnByDefault_BoundedGridPoint = (1 <<16);
    public static readonly int     SnapPointTypesOnByDefault_FacetVertexPoint = (1 <<17);
    public static readonly int        SnapPointTypesOnByDefault_DefiningPoint = (1 <<18);
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public static Point3d originPoint_1;
    public static Point3d originPoint_2;
    public static Point3d originPoint_3;
    public static Point3d originPoint_4;
    public static Vector3d directions_1;
    public static Vector3d directions_2;
    public static double length_1;
    public static double width_1;
    public static double height_1;
    public static double diameter_1;
    public static double height_2;
    public static double baseDiameter;
    public static double topDiameter;
    public static double height_3;
    public static double diameter_2;
  
    public BlockStylers()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = AppDomain.CurrentDomain.BaseDirectory + "BlockStylers.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        BlockStylers theBlockStylers = null;
        try
        {
            theBlockStylers = new BlockStylers();
            // The following method shows the dialog immediately
            theBlockStylers.Launch();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theBlockStylers != null)
                theBlockStylers.Dispose();
                theBlockStylers = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    //------------------------------------------------------------------------------
    //This method launches the dialog to screen
    //------------------------------------------------------------------------------
   /* public void Launch()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());

        }
    }*/

     public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
     {
         NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
         try
         {
             dialogResponse = theDialog.Launch();
         }
         catch (Exception ex)
         {
             //---- Enter your exception handling code here -----
             theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
         }
         return dialogResponse;
     }
    /* public Selection.Response Launch()
    {
        try
        {
           return theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            return Selection.Response.Cancel;
        }
    }*/

    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            tabControl = (NXOpen.BlockStyler.TabControl)theDialog.TopBlock.FindBlock("tabControl");
            tabBlock = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabBlock");
            grpOrigin = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpOrigin");
            spyPoint = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("spyPoint");
            grpDimensions = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpDimensions");
            dblLength = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblLength");
            dblWidth = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblWidth");
            dblHeight = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblHeight");
            tabCylinder = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabCylinder");
            grpAxis = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpAxis");
            spyVector = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("spyVector");
            spyPoint1 = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("spyPoint1");
            grpDimensions1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpDimensions1");
            dblDiameter = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblDiameter");
            dblHeight1 = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblHeight1");
            tabCone = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabCone");
            grpAxis1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpAxis1");
            spyVector1 = (NXOpen.BlockStyler.SpecifyVector)theDialog.TopBlock.FindBlock("spyVector1");
            spyPoint2 = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("spyPoint2");
            grpDimensions2 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpDimensions2");
            dblBaseDiameter = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblBaseDiameter");
            dblTopDiameter = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblTopDiameter");
            dblHeight2 = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblHeight2");
            tabSphere = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("tabSphere");
            grpCenterPoint = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpCenterPoint");
            spyPoint3 = (NXOpen.BlockStyler.SpecifyPoint)theDialog.TopBlock.FindBlock("spyPoint3");
            grpDimension = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("grpDimension");
            dblDiameter1 = (NXOpen.BlockStyler.DoubleBlock)theDialog.TopBlock.FindBlock("dblDiameter1");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {          

            int activeTab = tabControl.GetProperties().GetInteger("ActivePage");
                    
            if (activeTab == 0)
            { 
                if (length_1 <= 0 || width_1 <= 0 || height_1 <= 0)
                {
                    theUI.NXMessageBox.Show("Input Error", NXMessageBox.DialogType.Warning, "Length, Width, and Height must be greater than zero.");

                    return 1;
                }
                Class1.CreateBlock(originPoint_1, length_1.ToString(), width_1.ToString(), height_1.ToString());
                return 0;
            }
            else if (activeTab == 1)
            {
                if (diameter_1 <= 0 || height_2 <= 0)
                {
                    theUI.NXMessageBox.Show("Input Error", NXMessageBox.DialogType.Warning, "Cylinder Diameter and Height must be greater than zero.");

                    return 1;
                }
                Class1.CreateCylinder(directions_1, originPoint_2, diameter_1.ToString(), height_2.ToString());
                return 0;
            }
            else if (activeTab == 2)
            {
                if (baseDiameter <= 0 || topDiameter <= 0 || height_3 <= 0)
                {
                    theUI.NXMessageBox.Show("Input Error", NXMessageBox.DialogType.Warning, "All cone dimensions must be greater than zero.");

                    return 1;
                }
                Class1.CreateCone(directions_2, originPoint_3, baseDiameter.ToString(), topDiameter.ToString(), height_3.ToString());
                return 0;
            }
            else if (activeTab == 3)
            {
                if (diameter_2 <= 0)
                {
                    theUI.NXMessageBox.Show("Input Error", NXMessageBox.DialogType.Warning, "Sphere diameter must be greater than zero.");
                                        
                    return 1;
                }
                Class1.CreateSphere(originPoint_4, diameter_2.ToString());
                return 0;
            }


            //---- Enter your callback code here -----
            /* if(tabBlock != null && tabCylinder != null && tabCone != null)
             {
                 Class1.CreateSphere(originPoint_4, directions_2.ToString());
             }
             else if(tabBlock != null && tabCylinder != null && tabSphere != null)
             {
                 Class1.CreateCone(directions_2, originPoint_3, baseDiameter.ToString(), topDiameter.ToString(), height_3.ToString());
             }
             else if (tabBlock != null && tabCone != null && tabSphere != null)
             {
                 Class1.CreateCylinder(directions_1, originPoint_2, directions_1.ToString(), height_2.ToString());
             }
             else if(tabCylinder != null && tabCone != null && tabSphere != null)
             {
                 Class1.CreateBlock(originPoint_1, length_1.ToString(), width_1.ToString(), height_1.ToString());
             }*/
             /*Class1.CreateBlock(originPoint_1,length_1.ToString(),width_1.ToString(),height_1.ToString());
             Class1.CreateCylinder(directions_1, originPoint_2, diameter_1.ToString(), height_2.ToString());
             Class1.CreateCone(directions_2, originPoint_3, baseDiameter.ToString(),topDiameter.ToString(),height_3.ToString());
             Class1.CreateSphere(originPoint_4, diameter_2.ToString());*/
}
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    { 
        try
        {
            //bool isValid = false;

            int activeTab = tabControl.GetProperties().GetInteger("ActivePage");

            //PropertyList tabProps = tabControl.GetProperties();
            //int activeTab = tabProps.GetInteger("ActivePage");
            //tabProps.Dispose();

            //if (block == spyPoint || block == dblLength || block == dblWidth || block == dblHeight)
            //Block
            if (activeTab == 0)
            {
                originPoint_1 = spyPoint.GetProperties().GetPoint("Point");
                length_1 = dblLength.GetProperties().GetDouble("Value");
                width_1 = dblWidth.GetProperties().GetDouble("Value");
                height_1 = dblHeight.GetProperties().GetDouble("Value");

                //if (length_1 > 0 && width_1 > 0 && height_1 > 0)
                //    isValid = true;
            }

            //Cylinder
            //else if (block == spyVector || block == spyPoint1 || block == dblDiameter || block == dblHeight1)
            else if (activeTab == 1)
            {
                directions_1 = spyVector.GetProperties().GetVector("Vector");
                originPoint_2 = spyPoint1.GetProperties().GetPoint("Point");
                diameter_1 = dblDiameter.GetProperties().GetDouble("Value");
                height_2 = dblHeight1.GetProperties().GetDouble("Value");

                //if (diameter_1 > 0 && height_2 > 0)
                //    isValid = true;
            }

            //Cone
            //else if (block == spyVector1 || block == spyPoint2 || block == dblBaseDiameter || block == dblTopDiameter || block == dblHeight2)
            else if (activeTab == 2)
            {
                directions_2 = spyVector1.GetProperties().GetVector("Vector");
                originPoint_3 = spyPoint2.GetProperties().GetPoint("Point");
                baseDiameter = dblBaseDiameter.GetProperties().GetDouble("Value");
                topDiameter = dblTopDiameter.GetProperties().GetDouble("Value");
                height_3 = dblHeight2.GetProperties().GetDouble("Value");

                //if (baseDiameter > 0 && topDiameter > 0 && height_3 > 0)
                //    isValid = true;
            }

            //Sphere
            //else if (block == spyPoint3 || block == dblDiameter1)
            else if (activeTab == 3)
            {
                originPoint_4 = spyPoint3.GetProperties().GetPoint("Point");
                diameter_2 = dblDiameter1.GetProperties().GetDouble("Value");

                //if (diameter_2 > 0)
                //    isValid = true;
            }
            //PropertyList applyProps = theDialog.GetBlockProperties("Apply");
            //applyProps.SetLogical("Sensitive", isValid);
            //applyProps.Dispose();

            /* if (block == spyPoint)
             {
                 //---------Enter your code here-----------
                 spyPoint.GetProperties().GetPoint("Point");
             }
             else if(block == dblLength)
             {
                 //---------Enter your code here-----------
                 dblLength.GetProperties().GetDouble("Value");
             }
             else if(block == dblWidth)
             {
                 //---------Enter your code here-----------
                 dblWidth.GetProperties().GetDouble("Value");
             }
             else if(block == dblHeight)
             {
                 //---------Enter your code here-----------
                 dblHeight.GetProperties().GetDouble("Value");
             }
             else if(block == spyVector)
             {
             //---------Enter your code here-----------
                 spyVector.GetProperties().GetVector("Vector");
             }
             else if(block == spyPoint1)
             {
                 //---------Enter your code here-----------
                 spyPoint1.GetProperties().GetPoint("Point");
             }
             else if(block == dblDiameter)
             {
             //---------Enter your code here-----------
                 dblDiameter.GetProperties().GetDouble("Value");
             }
             else if(block == dblHeight1)
             {
             //---------Enter your code here-----------
                 dblHeight1.GetProperties().GetDouble("Value");
             }
             else if(block == spyVector1)
             {
                 //---------Enter your code here-----------
                 spyVector1.GetProperties().GetVector("Vector");
             }
             else if(block == spyPoint2)
             {
                 //---------Enter your code here-----------
                 spyPoint2.GetProperties().GetPoint("Point");
             }
             else if(block == dblBaseDiameter)
             {
                 //---------Enter your code here-----------
                 dblBaseDiameter.GetProperties().GetDouble("Value");
             }
             else if(block == dblTopDiameter)
             {
                 //---------Enter your code here-----------
                 dblTopDiameter.GetProperties().GetDouble("Value");
             }
             else if(block == dblHeight2)
             {
                 //---------Enter your code here-----------
                 dblHeight2.GetProperties().GetDouble("Value");
             }
             else if(block == spyPoint3)
             {
                 //---------Enter your code here-----------
                 spyPoint3.GetProperties().GetPoint("Point");
             }
             else if(block == dblDiameter1)
             {
                 //---------Enter your code here-----------
                 dblDiameter1.GetProperties().GetDouble("Value");
             }*/
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;
        try
        {
            errorCode = apply_cb();
            //---- Enter your callback code here -----
                   }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }
    
}
